word = input('Enter a word: ')
print("first character is",word[0])
print("second character is",word[1])
print("first 4 characters are",word[0:4])
print("every other character is",word[3:999999])
print("in reverse order",word[::-1])
